// Reservation Status
exports.RESERVATION_STATUS = {
    AWAITING_CUSTOMER: 1,
    USER_CANCELED: 2,
    TOLERANCE_TIME: 3,
    RESERVATION_EXPIRED: 4, 
    RESERVATION_FULFILLED: 5,
    RESTAURANT_CANCELED: 6,
    OTHER: 7,
    DEAL_EXPIRED: 8,
    DEAL_CANCELED: 9
}

exports.RESERVATION_TOLERANCE_MINUTES = 15;
